model-module: espnet.nets.pytorch_backend.e2e_tts_transformer:Transformer
embed-dim: 0
eprenet-conv-layers: 0
eprenet-conv-filts: 0
eprenet-conv-chans: 0
dprenet-layers: 2
dprenet-units: 256
adim: 384
aheads: 4
elayers: 6
eunits: 1536
dlayers: 6
dunits: 1536
postnet-layers: 5
postnet-filts: 5
postnet-chans: 256
use-masking: true
bce-pos-weight: 10.0
use-batch-norm: true
use-scaled-pos-enc: true
encoder-normalize-before: false
decoder-normalize-before: false
encoder-concat-after: false
decoder-concat-after: false
reduction-factor: 2
use-speaker-embedding: true
spk-embed-integration-type: add
freeze-mods: encoder.embed
batch-sort-key: output
batch-bins: 500000
transformer-init: pytorch
transformer-warmup-steps: 4000
transformer-lr: 1.0
initial-encoder-alpha: 1.0
initial-decoder-alpha: 1.0
eprenet-dropout-rate: 0.0
dprenet-dropout-rate: 0.5
postnet-dropout-rate: 0.5
transformer-enc-dropout-rate: 0.1
transformer-enc-positional-dropout-rate: 0.1
transformer-enc-attn-dropout-rate: 0.1
transformer-dec-dropout-rate: 0.1
transformer-dec-positional-dropout-rate: 0.1
transformer-dec-attn-dropout-rate: 0.1
transformer-enc-dec-attn-dropout-rate: 0.1
use-guided-attn-loss: false
opt: noam
accum-grad: 1
grad-clip: 1.0
weight-decay: 0.0
patience: 0
epochs: 200
save-interval-epoch: 10
report-interval-iters: 10
pretrained-model: downloads/tts1_en_ru/exp/train_pytorch_train_pytorch_transformer+spkemb/results/model.loss.best
